export const welcomeService = () => `
........................................................................................................................
........................................................................................................................
........................................................................................................................
.................................................                .......................................................
.............................................      .';clllc:;,.      ...................................................
..........................................     .;lkKXNWWWWWNXK0ko:.      ...............................................
.......................................    .'ckKNWWWXXNNXXNNNXKKXXKkl,.     ............................................
...................................     .;oONWWNXNWNXKNWNKKXNWNXK0KXNX0d;.     .........................................
................................     .:d0NWWWWXKKNWNK0XWWX00KXNWNX00KNWWN0x:.      .....................................
............................     .'cxKWWWWWWNK0KNWWX00XWWNX000XWWWNK00XWWWWNKkl,.     ..................................
.........................     .;oOXWWWWWWWNXK0KNWWNK0KNWWWN000KNWWWNK0KNWWWWWWNXOd:.      ..............................
......................    .'cxKNWWWWWWWNNK00KXNWWNK00XWWWWNK00KNWWWWNK0XNWWWWWWWWWNKkl,.     ...........................
...................    .,oOXWWWWWWWNNXKK00KXNWWNNK0KXWWWWWNK00KNWWWWWX0KNWWWWWWWWWWWWWX0d:.    .........................
.................    'lONWWWWWWWWNXXKKKXXNNWWWNXK0KNWWWWWWNK00XWWWWWWNKXNWWWWWWWWWWWWWWWWN0o,.    ......................
...............   .;xXWWWWWWWWWWWNNNNWWWWWWWNXKKXNWWWWWWWWX00KNWWWWWWNNNWWWWWWWWWWWWWWWWWWWWXkc.    ....................
.............   .;kNWWWWWWWWWWWWWWWWWWWWWWWWNNNNWWWWWWWWWNXXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOc.    ..................
...........    ;kNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOc.    ................
..........   .dXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXk,     ..............
.........   ;OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0c.    .............
.......    cKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd.     ...........
......   .lXMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd.     ..........
......   cKWWWWWWWWWWWWWWWWWWWWWWWWNXK0O0KNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXK0O0KXNWWWWWWWWWWWWWWWWWWWWWWWXd.      ........
.....   ,0WWWWWWWWWWWWWWWWWWWWWWNKxl;'....;lOXWWWWWWWWWWWWWWWWWWWWWWNKxl;'....;lOXWWWWWWWWWWWWWWWWWWWWWWKc       .......
.....  .dWWWWWWWWWWWWWWWWWWWWWWNk::dOkl.    .c0NWWWWWWWWWWWWWWWWWWWNk::dOkl.    .c0NWWWWWWWWWWWWWWWWWWWWNO'       ......
....   ,KWWWWWWWWWWWWWWWWWWWWWNk'.kWMMNo.     cKWWWWWWWWWWWWWWWWWWWk'.kWMMNo.     cKWWWWWWWWWWWWWWWWWWWWWXl       ......
....   lNWWWWWWWWWWWWWWWWWWWWWXo. :kK0x,      'kNWWWWWWWWWWWWWWWWWNo  :OKKx,      .kWWWWWWWWWWWWWWWWWWWWWNx.       .....
....  .dWWWWWWWWWWWWWWWWWWWWWWNo.   ..        'OWWWWWWWWWWWWWWWWWWNd.   ..        ,OWWWWWWWWWWWWWWWWWWWWWNO'        ....
....  .xWWWWWWWWWWWWWWWWWWWWWWW0:            .dXWWWWWWWWWWWWWWWWWWWK:            .dXWWWWWWWWWWWWWWWWWWWWWNO'        ....
....  .dNWWWWWWWWWWWWWWWWWWWNNNXOl'        .;kNWWWWWWWWWWWWWWWWWWWWWKd'.       .,xKXNNWWWWWWWWWWWWWWWWWWWNk'        ....
....   lXWWWWWWWWWWWWWWWWWWNXKKKKKOdc;,,;:oOXWWWWWWWWWWWWWWWWWWWWWWWWNKxc;,,;:lx0KKKKXNNWWWWWWWWWWWWWWWWNXd.        ....
....   ,0WWWWWWWWWWWWWWWWWNXKKKKKKKKK0000KKXWWWWWWWWWWWWWWWWWWWWWWWWWWNXKK000KKKKKKKKKXNWWWWWWWWWWWWWWWNNKc         ....
.....  .dNWWWWWWWWWWWWWWWWWNXKKKKKKKKKKKKKXNWN0xoooooooooooooooooodkXNNNXKKKKKKKKKKKKKXNWWWWWWWWWWWWWWNNXk'         ....
.....   ,ONWWWWWWWWWWWWWWWWWNNXXXXKKKKXXXNNWWK:................... .dNWWNNXXXXKKXXXXXNNWWWWWWWWWWWWWWNNN0c          ....
......   :KWWWWWWWWWWWWWWWWWWWWWNNNNNNNWWWWWWXo...'.............'. 'kNWWWWWWNNNNNNNWWWWWWWWWWWWWWWWWNNNKo.          ....
......    cKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKl.....';:cc:;;,.. .'kNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNKo.          .....
.......    :0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXx,..;loooooool;..c0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNKo.           .....
.........   ,kNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKx:'',;::;''',lOXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNXOc.           ......
..........   .oKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0xlc::coxkKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNKx,            .......
...........    ,xXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXk:.            ........
.............   .;kXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXXOc.             .........
...............   .;dKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNXKx:.              ..........
.................    'lkXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNXKOo,.               ...........
...................    .,lkKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNXKOo;.                .............
.....................     .':dOKNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNXX0xc,.                 ...............
.......................       .':ox0XXNNNNNNWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNXX0koc,.                   .................
.........................          .';coxO0KXXNNNNNNNNNNNNNNNNNNNNNXXXK0Okdl:,..                     ...................
............................             ..',:cloodxxxkkkkkkxxxddolc:;'..                         ......................
...............................                                                                .........................
...................................                                                        .............................
........................................                                              ..................................
..............................................                                  ........................................
........................................................................................................................
........................................................................................................................
........................................................................................................................

`;
